sudo: required

language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7

services:
  - docker

install:
  - docker pull couchdb:2.1.1
  - docker run -d -p 127.0.0.1:5984:5984 couchdb:2.1.1
  - sleep 5
  - "curl -X PUT http://127.0.0.1:5984/_users"
  - "curl -X PUT http://127.0.0.1:5984/_replicator"
  - "curl -X PUT http://127.0.0.1:5984/_global_changes"
