sudo: false

language: java

jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9
  - openjdk9
  - oraclejdk10
  - openjdk10
  - openjdk11
  
services:
  - docker
  
install:
  - docker pull couchdb:2.2.0
  - docker run -d -p 127.0.0.1:5984:5984 couchdb:2.2.0
  - sleep 5
  - "curl -X PUT http://127.0.0.1:5984/_users"
  - "curl -X PUT http://127.0.0.1:5984/_replicator"
  - "curl -X PUT http://127.0.0.1:5984/_global_changes"
